# Generated by Django 6.0 on 2025-12-23 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_question_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 30, 16, 40, 2, 602443, tzinfo=datetime.timezone.utc), verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
